image:
  repository: docker.io/brandawg93/peanut
  tag: 5.16.0@sha256:5a067c06814b193180c4e2487c2454f598702984c9f7fa6e1d2ffc8300ce0ed0
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688

persistence:
  config:
    enabled: true
    mountPath: "/config"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
