annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: custom
  truecharts.org/max_helm_version: "3.17"
  truecharts.org/max_kubernetes_version: 1.32.0
  truecharts.org/min_helm_version: "3.14"
  truecharts.org/min_kubernetes_version: 1.24.0
  truecharts.org/train: stable
apiVersion: v2
appVersion: 0.24.175
dependencies:
  - name: common
    version: 28.26.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 17.9.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
  - name: redis
    version: 17.13.1
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: ""
    tags: []
    import-values: []
  - name: mongodb
    version: 16.12.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mongodb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Advanced Template to create your own TrueCharts-based Charts
home: https://truecharts.org/charts/stable/app-template
icon: https://truecharts.org/img/hotlink-ok/chart-icons/app-template.webp
keywords:
  - custom
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: app-template
sources:
  - https://ghcr.io/linuxserver/jackett
  - https://github.com/truecharts/charts/tree/master/charts/stable/app-template
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/app-template
type: application
version: 15.24.7

