image:
  repository: ghcr.io/squat/generic-device-plugin
  pullPolicy: IfNotPresent
  tag: latest@sha256:62dda74362cc607b00d1ade291c192ea894d8bdc53a969ed5328b866b2988597

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --domain
            - truecharts.org
            - --device
            - |
              name: tun
              groups:
                - count: 1000
                  paths:
                    - path: /dev/net/tun
securityContext:
  container:
    readOnlyRootFilesystem: true
    privileged: true
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
persistence:
  dev:
    enabled: true
    type: hostPath
    hostPath: /dev
    mountPath: /dev
  device-plugin:
    enabled: true
    type: hostPath
    hostPath: /var/lib/kubelet/device-plugins
    mountPath: /var/lib/kubelet/device-plugins
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
