image:
  repository: docker.io/modem7/docker-rickroll
  pullPolicy: IfNotPresent
  tag: latest@sha256:c26da7b1ea13dbbbc75a28df0beea3f0c7e442f73b0c41911e85a2f6c77c2ec8
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10289
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            TITLE: "Rickroll"
            HEIGHT: "100vh"
            WIDTH: "100%"
            HEADLINE: ""
