image:
  repository: docker.io/rhasspy/wyoming-openwakeword
  pullPolicy: IfNotPresent
  tag: 2.0.0@sha256:3ef4a5453eb6437c1313bf190161e0b33663e99e8a9f970d44ddd8d80a646062

wyoming_openwakeword:
  model: ok_nabu
  preload_model: true
  custom_model:
    path: ""
  threshold: "0.5"
  trigger_level: 1
  debug: false

service:
  main:
    ports:
      main:
        port: 10400
        protocol: tcp
        targetPort: 10400
