image:
  repository: docker.io/domoticz/domoticz
  pullPolicy: IfNotPresent
  tag: 2025.2@sha256:8abff673c3bedf6e12998347f5ab0507af459d0fe177d6a786d5910cf0330a05
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10144
  comm1:
    enabled: true
    ports:
      comm1:
        enabled: true
        targetPort: 6144
        port: 6144
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # Set default http port. Container also has SSL_PORT variable for SSL.
            WWW_PORT: "{{ .Values.service.main.ports.main.port }}"
            # Set userdata path to match previous linuxserver.io default
            EXTRA_CMD_ARG: "-userdata {{ .Values.persistence.config.mountPath }}"
persistence:
  config:
    enabled: true
    mountPath: /opt/domoticz/userdata
