image:
  repository: docker.io/jonnyan404/verysync
  tag: v2.21.3@sha256:7f98a52599efec834b34d058200e0b8aed26702ee9d392e29deb05e5eef1b3c8
  pullPolicy: IfNotPresent
securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10193
  bt-udp1:
    enabled: true
    ports:
      bt-udp1:
        enabled: true
        port: 22037
        targetPort: 22037
        protocol: udp
  bt-udp2:
    enabled: true
    ports:
      bt-udp2:
        enabled: true
        port: 22027
        targetPort: 22027
        protocol: udp
  data:
    enabled: true
    ports:
      data:
        enabled: true
        port: 22330
        targetPort: 22330
persistence:
  data:
    enabled: true
    mountPath: "/data"
  sync:
    enabled: true
    mountPath: "/Sync"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            VUID: "{{- $.Values.securityContext.container.PUID -}}"
