image:
  repository: ghcr.io/pmmp/pocketmine-mp
  pullPolicy: IfNotPresent
  tag: 5.36.0@sha256:d3ead3256ec9eebcdca37b346513ff61ee993eac4bed8b19a2006c39a8d12923

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: udp
        targetPort: 19132
        port: 19132

workload:
  main:
    podSpec:
      containers:
        main:
          tty: true
          stdin: true
          probes:
            # -- Liveness probe configuration
            # @default -- See below
            liveness:
              enabled: false
            # -- Redainess probe configuration
            # @default -- See below
            readiness:
              enabled: false
            # -- Startup probe configuration
            # @default -- See below
            startup:
              enabled: false

persistence:
  data:
    enabled: true
    mountPath: "/data"
  plugins:
    enabled: true
    mountPath: "/plugins"
