image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.5.0@sha256:af7c6f8c8b2a2c86d41d7448c26549eb2ae74f000c1e7aa16f7ee761a1d38928
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
