image:
  repository: ghcr.io/kareadita/kavita
  pullPolicy: IfNotPresent
  tag: 0.8.8@sha256:1ac8a0a2eb4324186e13b0e7717e0eab0df499477801168f60ae84d13a449e9b
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"
  tmp:
    enabled: false
