image:
  repository: docker.io/collabora/code
  pullPolicy: IfNotPresent
  tag: 25.04.6.2.1@sha256:81173ae698bfc9035a64b970b6fe1ad0c6450dab3b3300e17c42337f537553c8
collabora:
  username: admin
  password: changeme
  interface: default
  dictionaries:
    - de_DE
    - en_GB
    - en_US
    - el_GR
    - es_ES
    - fr_FR
    - pt_BR
    - pt_PT
    - it
    - nl
    - ru
  server_name: example.com
  aliasgroup1: https://cloud.example.com
  ssl_enable: false
  ssl_termination: true
  no_gen_ssl: true
  extra_params:
    - --o:welcome.enable=false
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: collabora-config
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - SYS_CHROOT
                - MKNOD
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9980
        port: 9980
