image:
  repository: ghcr.io/tasmoadmin/tasmoadmin
  tag: v4.3.2@sha256:621eb1f03acfbeb7c859048f5726c03aa338613969e96a2c66872f912e664cc2
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TASMO_DEBUG: 1

service:
  main:
    ports:
      main:
        port: 9541
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data
