image:
  repository: docker.io/benbusby/whoogle-search
  tag: 1.1.0@sha256:842489a3e19d6636570240f93ed0147e16310c45b124746e1fc0c63bbf9ff916
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10052
        targetPort: 5000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WHOOGLE_CONFIG_COUNTRY: ""
            WHOOGLE_CONFIG_THEME: "dark"
            WHOOGLE_CONFIG_SAFE: true
            WHOOGLE_CONFIG_ALTS: false
            WHOOGLE_CONFIG_TOR: false
            WHOOGLE_CONFIG_NEW_TAB: false
            WHOOGLE_CONFIG_GET_ONLY: false
            WHOOGLE_CONFIG_URL: https://<your url>/
            WHOOGLE_CONFIG_STYLE: ""
