image:
  repository: ghcr.io/linuxserver/tvheadend
  pullPolicy: IfNotPresent
  tag: latest@sha256:2b0f51282bfcaa111875598488c0d8d99d91fd3f5aa7223790a79e705d76551b
service:
  main:
    ports:
      main:
        port: 9981
        targetPort: 9981
  htsp:
    enabled: true
    ports:
      htsp:
        enabled: true
        port: 9982
        targetPort: 9982
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
          env:
            RUN_OPTS: ""
