image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:6eed66d4059d03bd63fe4eeefb84c9f3f9f7030ebc0cb36bb6a5cf6469f1a6f6
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
