image:
  repository: ghcr.io/linuxserver/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.103.1@sha256:f59de3ab51259db4865c1d60980e8d99caf5395b647b72dc8152b04e6d483b17
# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
