image:
  repository: ghcr.io/flaresolverr/flaresolverr
  pullPolicy: IfNotPresent
  tag: v3.4.2@sha256:42ffb1cc56088899e91a7382bc611b00fa7cbd016accfed12c0695275ca18451
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8191
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            HOST: "0.0.0.0"
            TEST_URL: "https://www.google.com"
            BROWSER_TIMEOUT: 40000
            HEADLESS: true
            LOG_LEVEL: info
            LOG_HTML: false
            # At this time none of the captcha solvers work, defaults to none.
            CAPTCHA_SOLVER: none
persistence:
  config:
    enabled: true
    mountPath: /config
