image:
  repository: ghcr.io/linuxserver/rsnapshot
  pullPolicy: IfNotPresent
  tag: 1.4.5@sha256:a6cd15812b01bff735d9167beccdca484dde7f0def8a422b86f022b711012f1d
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
