image:
  repository: ghcr.io/anotherstranger/borg-server
  pullPolicy: IfNotPresent
  tag: 2.6.19@sha256:0e1c1c32ba3d6666208e5f2230a11f6f61076180d1124284942fdac6386edefe

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: tcp
        targetPort: 22
        port: 8022

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BORG_UID: "{{ .Values.securityContext.container.PUID }}"
            BORG_GID: "{{ .Values.securityContext.pod.fsGroup }}"
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL

persistence:
  borg:
    enabled: true
    mountPath: "/var/lib/docker-borg"
  backups:
    enabled: true
    mountPath: "/home/borg/backups"
  ssh:
    enabled: true
    mountPath: "/home/borg/.ssh"
