image:
  pullPolicy: IfNotPresent
  repository: docker.io/modem7/newyearcountdown
  tag: latest@sha256:6dc923e8f6ab4d9815bf91a7fe1492c82af06f2ff816086b469b5eba87a4080f
persistence: {}

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
