image:
  repository: docker.io/sentriz/gonic
  pullPolicy: IfNotPresent
  tag: v0.19.0@sha256:31e0df9b600ad4b49ea7cd4be198abe5fed33c11e00fbc368c3d2c2a8cde1fde

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10023

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GONIC_LISTEN_ADDR: ":{{ .Values.service.main.ports.main.port }}"
            GONIC_DB_PATH: "{{ .Values.persistence.data.mountPath }}/gonic.db"
            GONIC_CACHE_PATH: "{{ .Values.persistence.cache.mountPath }}"
            GONIC_PLAYLISTS_PATH: "{{ .Values.persistence.playlists.mountPath }}"
            GONIC_PODCAST_PATH: "{{ .Values.persistence.podcast.mountPath }}"
            GONIC_MUSIC_PATH: "{{ .Values.persistence.music.mountPath }}"

persistence:
  data:
    enabled: true
    mountPath: /data
  cache:
    enabled: true
    mountPath: /cache
  playlists:
    enabled: true
    mountPath: /playlists
  podcast:
    enabled: true
    mountPath: /podcast
  music:
    enabled: true
    mountPath: /music
