image:
  repository: ghcr.io/linuxserver/orcaslicer
  pullPolicy: IfNotPresent
  tag: 2.3.1@sha256:05f35e0b4bc6be1c80d16c5ef5635f12753e044d1d4a627cd2f8afc30d2e20d6
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
