image:
  repository: ghcr.io/linuxserver/projectsend
  pullPolicy: IfNotPresent
  tag: latest@sha256:b75dbce3af839b9181b310ea9bc186fb1113a8598379fe495e3b1abd3f7e9b5e
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 80
        port: 10127       
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            MAX_UPLOAD: 5000
            PHP_MEMORY_LIMIT: "512M"
            PHP_MAX_FILE_UPLOAD: 200
persistence:
  config:
    enabled: true
    mountPath: "/config"
  projectsend-config:
    enabled: true
    type: configmap
    objectName: projectsend-config
    mountPath: /config/projectsend/sys.config.php
    subPath: sys.config.php
    readOnly: true
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true
mariadb:
  enabled: true
  mariadbUsername: projectsend
  mariadbDatabase: projectsend
