image:
  repository: tccr.io/truecharts/magicmirror-2
  pullPolicy: IfNotPresent
  tag: latest@sha256:d39dd5ba0f16b97ce6da85803c780fa6880569dbcce141c6a4e4700079501625

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

magicmirror:
  force_update: false
  force_update_modules: false
  language: en
  time_format: "24"
  units: metrics
  ip_whitelist: []
  mm2_modules: [{ module: "clock", position: "top_left"}]
  mm2_modules_dl: []

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-magicmirror-env'

probes:
  liveness:
    type: HTTP
    path: /
  readiness:
    type: HTTP
    path: /
  startup:
    type: HTTP
    path: /

service:
  main:
    ports:
      main:
        port: 10590
        protocol: HTTP

persistence:
  config:
    enabled: true
    mountPath: /magicmirror2
  configfile:
    enabled: true
    type: custom
    mountPath: /magicmirror2/config/config.js
    subPath: config.js
    defaultMode: "0770"
    volumeSpec:
      configMap:
        name: '{{ printf "%s-magicmirror-config" (include "tc.common.names.fullname" .) }}'
  modulesfile:
    enabled: true
    type: custom
    mountPath: /magicmirror2/modules/modules.txt
    subPath: modules.txt
    defaultMode: "0770"
    volumeSpec:
      configMap:
        name: '{{ printf "%s-magicmirror-modules" (include "tc.common.names.fullname" .) }}'

portal:
  enabled: true
