image:
  repository: ghcr.io/linuxserver/foldingathome
  pullPolicy: IfNotPresent
  tag: 8.4.9@sha256:1d939702025de8e90f25d8857f177e08c0092e31e095c70ca7d8ccc1153ed47d
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        targetPort: 7396
        port: 7396
  control:
    enabled: true
    ports:
      control:
        enabled: true
        targetPort: 36330
        port: 36330
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true
