image:
  repository: docker.io/aeonlucid/impostor
  pullPolicy: IfNotPresent
  tag: v1.10.4@sha256:71a50fd5eb9117eeac4c194d7c01c6488ea1372ea0e59220e00b2c5dbe186bab
nightlyImage:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:fc3b143df2a3545f8b64af2fad251a3d1e4adabc05fed7b9cfe4d01b0a4a6107
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: udp
        port: 22023
        targetPort: 22023

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            IMPOSTOR_Server__PublicIp: "127.0.0.1"
            IMPOSTOR_Server__ListenIp: "0.0.0.0"
            IMPOSTOR_AntiCheat__Enabled: true
            IMPOSTOR_AntiCheat__BanIpFromGame: true
            IMPOSTOR_Debug__GameRecorderEnabled: false
            IMPOSTOR_Debug__GameRecorderPath: ""
updated: true
