image:
  pullPolicy: IfNotPresent
  repository: docker.io/tracksapp/tracks
  tag: latest@sha256:de54e3af5af086b0d88487ef8f7c3b70904faae4a38b476d0631da125bc57b35
persistence: {}

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BUNDLE_WITHOUT: ""
            DATABASE_ENCODING: utf8
            DATABASE_HOST: 10.0.0.10
            DATABASE_NAME: tracks
            DATABASE_PASSWORD: password
            DATABASE_PORT: "3306"
            DATABASE_TYPE: mysql2
            DATABASE_USERNAME: tracks
            RAILS_ENV: production
