image:
  repository: docker.io/balabit/syslog-ng
  pullPolicy: IfNotPresent
  tag: 4.10.2@sha256:4c080c73e493b227b0cd1d38d26f13ebd1f8a3bba4046ee52f9e92b963da2b4d
service:
  main:
    ports:
      main:
        targetPort: 601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: udp
        targetPort: 514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
