image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: 3@sha256:cd92709b4191c5779cd7215ccd695db6c54652e7a62843197e367427efb84d0e
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
