image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.8.3@sha256:526bbbaca7d2f16290e75a28bedbdcca674631e5ca5d7a0600b4dc46784e5360
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
