image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/booklore-app/booklore
  tag: v1.8.1@sha256:6b2250cd1a8e13f4e458b5dd2ffe30ed9696482061f27954a97463ffcce677a2
service:
  main:
    ports:
      main:
        protocol: http
        port: 6060
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: jdbc-mariadb
            DATABASE_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DATABASE_PASSWORD: "{{ .Values.mariadb.password }}"
            BOOKLORE_PORT: "{{ .Values.service.main.ports.main.port }}"
persistence:
  data:
    enabled: true
    mountPath: /app/data
  varrun:
    enabled: false
mariadb:
  enabled: true
  mariadbUsername: booklore
