image:
  repository: docker.io/anirdev/slink
  pullPolicy: IfNotPresent
  tag: v1.7.3@sha256:4dc9e1849a0a814d51c031f1e3870b9c58767192b3fff4f46a89005879ca0042
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
            USER_APPROVAL_REQUIRED: true
            IMAGE_MAX_SIZE: "15M"
persistence:
  database:
    enabled: true
    mountPath: "/app/var/data"
  images:
    enabled: true
    mountPath: "/app/slink/images"
ingress:
  main:
    required: true
