image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: 1.2.1@sha256:f0947d6eac12a4561a67c1d1d2088fbcd95291019259c373e327e8b15edf3e22

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/api/v2/heartbeat"
            readiness:
              path: "/api/v2/heartbeat"
            startup:
              path: "/api/v2/heartbeat"
          env:
            IS_PERSISTENT: true

persistence:
  config:
    enabled: true
    mountPath: "/chroma/chroma"
